name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
    - 'src/sdk/PnP.Core/**'
    - 'src/sdk/PnP.Core.Auth/**'
    - 'src/sdk/PnP.Core.Test/**'
    - 'src/sdk/PnP.Core.Auth.Test/**'
  pull_request:
    branches: [ dev ]
    paths:
    - 'src/sdk/PnP.Core/**'
    - 'src/sdk/PnP.Core.Auth/**'
    - 'src/sdk/PnP.Core.Test/**'
    - 'src/sdk/PnP.Core.Auth.Test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Wait for actions to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with: 
        ref: dev
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Test and Coverage report 📝
      run: |
        dotnet build
        dotnet test --collect:"XPlat Code Coverage"
      working-directory: src/sdk
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: /**/*coverage*.xml
        flags: ${{ runner.os }},netcore${{ matrix.dotnet }}      
