name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
    - 'src/sdk/PnP.Core/**'
    - 'src/sdk/PnP.Core.Auth/**'
    - 'src/sdk/PnP.Core.Test/**'
    - 'src/sdk/PnP.Core.Auth.Test/**'
  pull_request:
    branches: [ dev ]
    paths:
    - 'src/sdk/PnP.Core/**'
    - 'src/sdk/PnP.Core.Auth/**'
    - 'src/sdk/PnP.Core.Test/**'
    - 'src/sdk/PnP.Core.Auth.Test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Wait for actions to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with: 
        ref: dev
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Test and Coverage report 📝
      run: |
        dotnet build
        dotnet test --collect:"XPlat Code Coverage"
        find ./PnP.Core.Test -name "coverage.cobertura.xml" -type f -exec cp {} ./ \;
        bash <(curl -s https://codecov.io/bash) -Z -f coverage.cobertura.xml -t $CODECOV_TOKEN
        rm coverage.cobertura.xml
        find ./PnP.Core.Auth.Test -name "coverage.cobertura.xml" -type f -exec cp {} ./ \;
        bash <(curl -s https://codecov.io/bash) -Z -f coverage.cobertura.xml -t $CODECOV_TOKEN
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      working-directory: src/sdk
